# Generated by Django 5.1.7 on 2025-03-16 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vision_logs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Entry',
            new_name='Content',
        ),
    ]
