# Generated by Django 5.1.7 on 2025-03-20 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vision_logs', '0003_alter_content_options_remove_content_date_added'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='content',
            new_name='topic',
        ),
    ]
