# Generated by Django 5.1.7 on 2025-03-20 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vision_logs', '0004_rename_content_content_topic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='topic',
            new_name='content',
        ),
    ]
